[package]
name = "rookiepy"
version = "0.1.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rookiepy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rookie = { path = "../../rookie-rs" }